### ISSUE TITLE
TvHeadendCli for other platforms

### ISSUE THREAD

**Issue by Lonerider2010** [ChrWieg/TvHeadendCli#2]
As I understand, TvHeadendCli is available for the Windows-Platform only.
On the other hand, Tv-Browser as well as TvHeadend are available for different platforms like macOS and Linux. So I would really appreciate to have TvHeadendCli available for these platforms, too. Especially for Linux, all platforms, in my case.
Please tell me, if I can help/support with this issue.

**Comment by ChrWieg** [comment]
Yes, you are right, this tool is written in C# only for Windows . Since I don't have any experience with Java, I don't really like the idea to rewrite the whole program, sorry!
If somebody else would like to do it, feel free to use the project as template.

**Comment by ChrWieg** [comment]
Sorry, can't solve this.
